spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hello?useUnicode=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
mybatis: 
  mapper-locations:
  - classpath:com/example/test/quartz/mapper/*.xml
  type-aliases-package: com.example.test.quartz.entity